project_id = "orzihyioizslidrqnyio"

[functions.followup-boss-event]
verify_jwt = false

[functions.repliers-proxy]
verify_jwt = false

[functions.repliers-market-stats]
verify_jwt = false

[functions.repliers-webhook]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.optimize-image]
verify_jwt = true

[functions.migrate-blogs]
verify_jwt = true

[functions.generate-city-content]
verify_jwt = false

[functions.analyze-competitor-seo]
verify_jwt = false

[functions.generate-sitemap-content]
verify_jwt = false

[functions.generate-sitemap-listings]
verify_jwt = false

[functions.generate-facebook-catalog]
verify_jwt = false

[functions.generate-google-real-estate-feed]
verify_jwt = false

[functions.generate-page-feed]
verify_jwt = false

[functions.generate-ad-customizers]
verify_jwt = false
