project_id = "orzihyioizslidrqnyio"

[functions.followup-boss-event]
verify_jwt = false

[functions.repliers-proxy]
verify_jwt = false

[functions.optimize-image]
verify_jwt = true

[functions.migrate-blogs]
verify_jwt = true

[functions.generate-city-content]
verify_jwt = false

[functions.analyze-competitor-seo]
verify_jwt = false
